config/routes.rb
# == Route Map
#
#                    Prefix Verb URI Pattern                                                                              Controller#Action
#                   artists GET  /artists(.:format)                                                                       artists#index
#        rails_service_blob GET  /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET  /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET  /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT  /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/artists', to: 'artists#index'
  get '/artists/new', to: 'artists#new', as: 'new_artist'
  post '/artists', to: 'artists#create'
  get '/artists/:id', to: 'artists#show', as: 'artist'
  get '/artists/:id/edit', to: 'artists#edit', as: 'edit_artist'
  patch '/artists/:id', to: 'artists#update'
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id          :integer          not null, primary key
#  image_url   :string
#  name        :string
#  released_at :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  artist_id   :integer
#

class Album < ActiveRecord::Base
  belongs_to :artist
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  image_url  :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Artist < ActiveRecord::Base
	has_many :albums
    has_many :songs
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id          :integer          not null, primary key
#  name        :string
#  number      :integer
#  preview_url :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  album_id    :integer
#

class Song < ActiveRecord::Base
	belongs_to :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path, notice: "El artista fue creado con EXITO!"
    else
      render :new
    end
  end

  def show
    @artist = Artist.find(params[:id])
    @albums = @artist.albums.ids
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update(artist_params)
      redirect_to artists_path, notice: "El artista fue modificado con EXITO!"
    else
      render :edit
    end
  end

  private
  def artist_params
    params.require(:artist).permit(:name, :image_url)
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
	def form_title
		@artist.new_record? ? "Publicar artista" : "Modificar artista"
	end
end

app/views/artists/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<h1><%= form_title %></h1>
			<%= form_for @artist do |f| %>
               <div class="form-group">
            	   <%= f.text_field :name, class: "form-control input-lg", placeholder: "Ingresa el nombre del artista" %>
            	</div>
            	<div class="form-group">
            	   <%= f.url_field :image_url, class: "form-control input-lg", placeholder: "Ingresa la url fotografia del album" %>
                </div>   
                <div>
                	<%= f.submit form_title, class:"btn btn-primary btn-lg btn-block" %>
                </div>
			<% end %>
		</div>
	</div>
</div>

app/views/artists/edit.html.erb
<%= render 'form' %>

app/views/artists/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
    	<div class="text-right">
    		<%= link_to "Publicar artista", new_artist_path, class:"btn btn-primary" %>
    	</div>

      <div class="artists row">
        <% @artists.each do |artist| %>
          <div class="col-sm-3">
            <div class="thumbnail">
              <img src="<%= artist.image_url %>" alt="<%= artist.name %>">
              <div class="caption">
                <h3 class="text-center"><%= artist.name %></h3>
                <%= link_to "Ver más", artist, class: "btn btn-primary btn-block" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/artists/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<h1>Artista</h1>
			<%= form_for @artist do |f| %>
               <div class="form-group">
            	   <%= f.text_field :name, class: "form-control input-lg", placeholder: "Ingresa el nombre del artista" %>
            	</div>
            	<div class="form-group">
            	   <%= f.url_field :image_url, class: "form-control input-lg", placeholder: "Ingresa la url fotografia del album" %>
                </div>   
                <div>
                	<%= f.submit "Publicar artista", class:"btn btn-primary btn-lg btn-block" %>
                </div>
			<% end %>
		</div>
	</div>
</div>

app/views/artists/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-7">
      <h1><%= @artist.name %></h1>
      <hr>
      <h3>Albums (<%= @artist.albums.count %>)</h3>
      <div class="row" style="margin-top: 30px;">
        <% @artist.albums.each do |album| %>
          <div class="col-sm-3">
          <div class="thumbnail" style="height: 225px;">
            <img src="<%= album.image_url %>" alt="<%= album.name %>">
            <div class="caption">
              <h5><%= album.name %></h5>
              <p><%= l album.released_at, format: '%Y' if album.released_at %></p>
            </div>
          </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-sm-4 col-sm-offset-1">
      <img src="<%= @artist.image_url %>" alt="<%= @artist.name %>" class="pull-right img-responsive img-rounded">
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpotifyChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>


    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Real Musica</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="#">Artistas</a></li>
        <li class="active"><a href="#">Mi Musica</a></li>


        
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Mi Cuenta</a></li>
        </ul>
      </div>
    </nav>

  	<% if flash[:notice] %>
  		<div class="alert alert-info"> <%= flash[:notice] %></div>
  	<% end %>
    <%= yield %>
  </body>
</html>